theme = "everforest_dark"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor]
line-number = "relative"
bufferline = "multiple"
shell =["nu"]

[editor.lsp]
display-signature-help-docs = false

[keys.normal]
A-q = ":reflow"

[keys.insert]
A-q = ":reflow"

